import '../../models/jellyfin_session.dart';
import 'jellyfin_api.dart';

/// The single seam through which Linthra talks HTTP to a Jellyfin server.
///
/// Every request to Jellyfin goes through this interface, so the rest of the
/// app (authenticator, source, settings) depends only on it — never on `http`,
/// URLs, headers, or JSON. That keeps networking swappable and, crucially,
/// lets tests drive the whole feature with a fake client and canned responses
/// (no real server, no Cloudflare).
///
/// Implementations throw a [JellyfinException] (with a friendly message and a
/// [JellyfinErrorKind]) for every failure, and must never put the password or
/// access token into an exception, log, or any other output.
abstract interface class JellyfinClient {
  /// Confirms an address is a reachable Jellyfin server and returns its public
  /// info. Backs the "Test connection" action; needs no credentials.
  Future<JellyfinServerInfo> fetchServerInfo(String baseUrl);

  /// Exchanges a username + password for an access token.
  ///
  /// [deviceId] is generated by the caller (the authenticator) so the same id
  /// can be reused for the resulting session's later requests. The password is
  /// used only for this call and is never persisted by anything downstream.
  Future<JellyfinAuthResult> authenticateByName({
    required String baseUrl,
    required String username,
    required String password,
    required String deviceId,
  });

  /// Lists library items of one [kind] for the signed-in user in [session].
  Future<List<JellyfinItemDto>> fetchItems(
    JellyfinSession session, {
    required JellyfinItemKind kind,
  });

  /// Confirms [session] is still accepted by the server — the token is valid
  /// and the server is reachable — without fetching anything large.
  ///
  /// Backs the pre-stream check the playback resolver runs so it can report an
  /// expired session or an unreachable server precisely. Throws a
  /// [JellyfinException] ([JellyfinErrorKind.unauthorized] for an expired token,
  /// [JellyfinErrorKind.notReachable] when offline, …) on failure.
  Future<void> verifySession(JellyfinSession session);

  /// Probes a minted stream [url] with a tiny ranged request to confirm the
  /// server returns playable audio *before* the URL is handed to the audio
  /// engine, returning the observed status and content type. Redirects (e.g.
  /// from Cloudflare) are followed, so the result reflects the final response.
  ///
  /// Throws a [JellyfinException] only for transport failures
  /// ([JellyfinErrorKind.notReachable]); a non-2xx status is returned in the
  /// [JellyfinStreamProbe] for the caller to classify, not thrown. The [url]
  /// carries the session token, so it must never be logged or placed in a
  /// thrown error.
  Future<JellyfinStreamProbe> probeStream(Uri url);
}
